[package]

name = "git2"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/APL2"
readme = "README.md"
keywords = ["git"]
repository = "https://github.com/alexcrichton/git2-rs"
homepage = "https://github.com/alexcrichton/git2-rs"
documentation = "http://alexcrichton.com/git2-rs"
description = """
Bindings to libgit2 for interoperating with git repositories. This library is
both threadsafe and memory safe and allows both reading and writing git
repositories.
"""

[dependencies.libgit2-sys]
path = "libgit2-sys"
version = "*"

[dependencies.url]
git = "https://github.com/servo/rust-url"
